/**
 * ============================================================================
 *  OUTBREAK RADAR - SHARED CONTRACT
 * ============================================================================
 *  FROZEN. Do not edit this file without telling the whole team first.
 *
 *  Three people build against these types in parallel:
 *    - the detection engine (lib/detect/) produces them
 *    - the dashboard (app/radar/) and drill-down (app/radar/[id]/) consume them
 *
 *  If a shape here changes after hour 1, somebody's work gets thrown away.
 *  Need something added? Say so in the group chat, add it as OPTIONAL, and
 *  never rename or remove an existing field.
 * ============================================================================
 */

/* ---------------------------------------------------------------- domain -- */

export type NodeType = 'source' | 'mess' | 'tank' | 'floor' | 'filter';
export type UserRole = 'student' | 'doctor' | 'warden';
export type Residency = 'hosteller' | 'day_scholar';
export type ReportSource = 'self' | 'doctor';

/** watch = dashboard only, never notifies. alert = waiting on a human.
 *  confirmed = human said yes, advisory sent. resolved = cause found and logged. */
export type ClusterStatus = 'watch' | 'alert' | 'confirmed' | 'dismissed' | 'resolved';

export type Hypothesis = 'water' | 'food' | 'mess_water' | 'unresolved';

export type ScenarioId = 'quiet' | 'filter_fault' | 'food' | 'coincidence';

export type Symptom =
  | 'vomiting'
  | 'diarrhea_watery'
  | 'diarrhea_bloody'
  | 'nausea'
  | 'abdominal_cramps'
  | 'fever'
  | 'headache'
  | 'dehydration';

export const SYMPTOM_LABELS: Record<Symptom, string> = {
  vomiting: 'Vomiting',
  diarrhea_watery: 'Diarrhoea (watery)',
  diarrhea_bloody: 'Diarrhoea (bloody)',
  nausea: 'Nausea',
  abdominal_cramps: 'Abdominal cramps',
  fever: 'Fever',
  headache: 'Headache',
  dehydration: 'Signs of dehydration',
};

/** Privacy rule, non-negotiable: never render an exact count below this.
 *  A warden who sees "1 case on Floor 2 Filter A" knows exactly who that is. */
export const SUPPRESSION_THRESHOLD = 3;

/* ------------------------------------------------------- infrastructure -- */

export interface InfraNode {
  id: string;
  name: string;                 // "Filter 3A", "Tank B", "Mess"
  type: NodeType;
  parentId: string | null;
  servesRooms: string | null;   // "301-320" - filter nodes only
  exposedPopulation: number;    // THE DENOMINATOR. Never compare raw counts.
  blockLabel: string | null;    // "Block B"
  floorLabel: string | null;    // "Floor 3"
}

/* ------------------------------------------- campus elevation (hero view) -- */

/** One filter half of one floor - the smallest rendered cell. */
export interface ElevationCell {
  nodeId: string;
  label: string;                // "3A"
  servesRooms: string | null;
  caseCount: number;            // weighted (doctor 1.0, self 0.6), rounded 1dp
  exposedPopulation: number;
  attackRate: number;           // caseCount / exposedPopulation - COLOUR BY THIS
  suppressed: boolean;          // below SUPPRESSION_THRESHOLD, render "<3"
  isFlagged: boolean;           // inside the top cluster subtree
}

export interface ElevationFloor {
  nodeId: string;
  label: string;                // "Floor 3"
  filters: ElevationCell[];     // always exactly 2
  caseCount: number;
  attackRate: number;
  suppressed: boolean;
  isFlagged: boolean;
}

export interface ElevationBlock {
  nodeId: string;               // the TANK node id (one tank per block)
  label: string;                // "Block B"
  tankName: string;             // "Tank B"
  floors: ElevationFloor[];     // highest floor FIRST, so it renders as a building
  caseCount: number;
  attackRate: number;
  suppressed: boolean;
  isFlagged: boolean;
}

/** Renders as one wide bar spanning underneath every block - it is shared by
 *  all of them, and that is the whole point of drawing it that way. */
export interface ElevationMess {
  nodeId: string;
  label: string;                // "Mess"
  filters: ElevationCell[];     // M1, M2
  caseCount: number;
  attackRate: number;
  suppressed: boolean;
  isFlagged: boolean;
}

/** Day scholars eat at the mess and drink no hostel tank water. If they are
 *  sick, the water hypothesis is near-eliminated campus-wide. Free control group. */
export interface ElevationDayScholars {
  caseCount: number;
  exposedPopulation: number;
  attackRate: number;
  suppressed: boolean;
}

export interface CampusElevation {
  blocks: ElevationBlock[];
  mess: ElevationMess;
  dayScholars: ElevationDayScholars;
  /** Max attack rate anywhere this run - use to normalise the colour scale. */
  maxAttackRate: number;
}

/* -------------------------------------------------------------- clusters -- */

export interface Cluster {
  id: string;
  /** Water clusters point at an infra node; food clusters point at a meal. */
  nodeId: string | null;
  mealId: string | null;
  name: string;                 // "Filter 3A" or "Tuesday dinner"
  hypothesis: Hypothesis;
  status: ClusterStatus;

  windowStart: string;          // ISO
  windowEnd: string;            // ISO
  windowHours: number;

  // --- spatial evidence
  observed: number;             // weighted case count in subtree
  expected: number;             // occupancy x baseline x window
  llr: number;                  // Kulldorff log-likelihood ratio
  pSpatial: number;             // permutation p-value  <-- the headline number
  qValue: number;               // Benjamini-Hochberg adjusted
  significant: boolean;         // survived FDR at fdrQ

  // --- cohort evidence (2x2). Null when no meal association was computed.
  relativeRisk: number | null;
  exposedSick: number;
  exposedWell: number;
  unexposedSick: number;
  unexposedWell: number;

  // --- temporal evidence. Sharp curve => food. Smeared => water.
  medianIncubationHours: number | null;
  curveWidthHours: number | null;

  /** Plain-English arbitration, stronger hypothesis. Render verbatim. */
  verdict: string;
  /** The weaker hypothesis, shown underneath so we never hide the alternative. */
  alternative: string | null;

  caseIds: string[];
  confirmedBy: string | null;
}

/* ------------------------------------------------------------ epi curve -- */

export interface EpiCurveBucket {
  bucketStart: string;                 // ISO
  label: string;                       // "Tue 18:00"
  byBlock: Record<string, number>;     // "Block A" -> 3  (stack these)
  total: number;
}

export interface MealMarker {
  mealId: string;
  label: string;                       // "Tue dinner"
  at: string;                          // ISO - draw a reference line here
}

export interface EpiCurve {
  buckets: EpiCurveBucket[];
  blocks: string[];                    // stable series keys for stacking
  mealMarkers: MealMarker[];
  bucketHours: number;                 // 6
}

/* ----------------------------------------------------------------- cases -- */

export interface CaseRow {
  id: string;
  /** Already redacted per role by the API. Wardens get "Student #412",
   *  doctors get the real name. Never do this redaction in the UI. */
  studentLabel: string;
  roomNumber: string | null;
  blockLabel: string | null;
  floorLabel: string | null;
  filterName: string | null;
  residency: Residency;
  symptoms: Symptom[];
  onsetTime: string;                   // ISO
  reportTime: string;                  // ISO
  severity: number;                    // 1-5
  reportedBy: ReportSource;
  sourceWeight: number;                // doctor 1.0 / self 0.6
  /** Reported after this student was already notified about a cluster.
   *  EXCLUDED from detection (rumour-amplifier control), still shown for care. */
  prompted: boolean;
}

/* ----------------------------------------------------- permutation test -- */

/** The Challenge Question, as data. Hold the case count fixed, redistribute
 *  cases across rooms proportional to occupancy, N times, and see how often
 *  chance alone produces a cluster this tight. */
export interface PermutationSummary {
  replicates: number;                  // 999
  observedLlr: number;
  /** Every null replicate max-LLR. Draw the histogram from this and mark
   *  observedLlr in the tail - this is the money visual in the whole product. */
  nullLlrs: number[];
  pValue: number;
  rank: number;                        // how many nulls beat the observed
}

/* -------------------------------------------------- meal association 2x2 -- */

export interface MealAssociation {
  mealId: string;
  label: string;                       // "Tue dinner"
  items: string[];
  exposedSick: number;
  exposedWell: number;
  unexposedSick: number;
  unexposedWell: number;
  attackRateExposed: number;
  attackRateUnexposed: number;
  relativeRisk: number;
  pValue: number;
}

/* ---------------------------------------------------------- intervention -- */

export type InterventionKind = 'water_test' | 'kitchen_inspection' | 'filter_replaced';

export interface Intervention {
  id: string;
  clusterId: string;
  kind: InterventionKind;
  tds: number | null;                  // mg/L
  residualChlorine: number | null;     // mg/L
  turbidity: number | null;            // NTU
  coliformPositive: boolean | null;
  outcome: string | null;
  causeCode: string | null;            // the ground-truth label we learn from
  performedBy: string | null;
  performedAt: string;                 // ISO
}

/* ------------------------------------------------------- engine results -- */

export interface DetectionResult {
  scenario: ScenarioId;
  runAt: string;                       // ISO
  windowHours: number;

  totalCases: number;
  totalPopulation: number;
  baselineRatePerDay: number;

  /** Ranked, most significant first. May be empty - that is a valid result,
   *  and in the quiet and coincidence scenarios it is the CORRECT one. */
  clusters: Cluster[];
  topCluster: Cluster | null;

  elevation: CampusElevation;
  epiCurve: EpiCurve;
  permutation: PermutationSummary | null;

  /** What a naive count-threshold system would have done with this same data.
   *  In the coincidence scenario this is true while our own result is only
   *  watch - render the contrast, it is the entire pitch. */
  naiveThresholdWouldAlert: boolean;
  naiveThresholdNodeName: string | null;

  nodesTested: number;
  fdrQ: number;
  /** One-sentence summary for the top of the dashboard. Render verbatim. */
  headline: string;
}

export interface ClusterDetail {
  cluster: Cluster;
  cases: CaseRow[];
  epiCurve: EpiCurve;
  permutation: PermutationSummary;
  interventions: Intervention[];
  mealTable: MealAssociation[];
}

/* ----------------------------------------------------------- API shapes -- */

/** POST /api/seed   body: SeedRequest */
export interface SeedRequest {
  scenario: ScenarioId;
}
export interface SeedResponse {
  ok: boolean;
  scenario: ScenarioId;
  students: number;
  reports: number;
  days: number;
}

/** POST /api/detect -> DetectionResult   (GET returns the last run) */
/** GET  /api/clusters/[id] -> ClusterDetail */

/** POST /api/reports */
export interface CreateReportRequest {
  studentId: string;
  symptoms: Symptom[];
  onsetTime: string;                   // ISO
  severity: number;                    // 1-5
  mealsEaten: string[];                // meal ids, last 72h
  reportedBy: ReportSource;
  doctorNotes?: string;
}
export interface CreateReportResponse {
  ok: boolean;
  reportId: string;
}

/* --------------------------------------------------------- scenario meta -- */

export interface ScenarioMeta {
  id: ScenarioId;
  label: string;
  blurb: string;
  expected: string;
}

export const SCENARIOS: ScenarioMeta[] = [
  {
    id: 'quiet',
    label: 'Quiet baseline',
    blurb: 'Five scattered, unrelated stomach upsets.',
    expected: 'System stays silent.',
  },
  {
    id: 'filter_fault',
    label: 'Filter fault',
    blurb: 'Nine cases in 48h, all under one floor filter, smeared onset.',
    expected: 'Localises to Filter 3A, p is about 0.002.',
  },
  {
    id: 'food',
    label: 'Food batch',
    blurb: 'Fourteen cases across three blocks and day scholars, sharp onset.',
    expected: 'Localises to Tuesday dinner, RR is about 7.',
  },
  {
    id: 'coincidence',
    label: 'Coincidence trap',
    blurb: 'Seven cases that land in one block purely by chance.',
    expected: 'A threshold system alerts. We hold at watch, p is about 0.31.',
  },
];
